project:
    type: tufte
book:
  title: |
    Tufte-Quarto Extension\
    Documentation
  title-short: $$~$$ # title-short used in the pdf head
  output-file: TufteStyledBook
  author: Fred Guth
  publisher: The Publisher
  date-format: MMMM, YYYY
  chapters:
    - index.qmd
    # - 02-Main/preface.qmd
    # - part: repo.qmd
    # - part: Customizing
    #   chapters:
    #   - 02-Main/document.qmd              
    #   - 02-Main/website.qmd              
    # - 03-Back/notation.qmd
    # - 03-Back/acronyms.qmd
    # - 03-Back/colophon.qmd
  # appendices:
  #   - 03-Back/ack.qmd
  #   - 03-Back/colophon.qmd
format:
  pdf:
    keep-tex: true