---
title: Probability Theory
description: |
    A wise man proportions his belief to the evidence. 
    --- David Hume
fig-cap-location: bottom
---
\epigraph{A wise man proportions his belief to the evidence.}{--- David Hume}

::: {.content-hidden when-format="html"}

# Probability Theory {#ch:probability}

:::


In this chapter, propositional calculus and probability theory are derived from a list of desired characteristics for sceptical agents.

## From Language to Probability {#sec:language_probability}

### Formal Languages {#sec:formal_language}

We, as intelligent agents, do not know how Nature is; we only know how we perceive it. Our ideas are mental pictures of how we imagine Nature. Like in the story of the blind men and the elephant ([\[blind_men\]][1]), how do we know that our model is the same as someone else's? *Communicating*. We need to communicate with each other to check if our mental picture of Nature, our model, is consistent with the experience of others.[^31]

We use language to describe Nature. However, natural languages, like English, German, Portuguese, are ambiguous, and we need contextual clues and other information to more clearly communicate meaning. To avoid this, an intelligent agent uses formal language.

A *formal language* is a mathematical tool created for precise communication about a specific subject. For example, arithmetic is a language for calculations. Chemists have a language that represents the chemical structures of molecules. Programming languages are formal languages that express computations. In a nutshell, a formal language is a set of words (strings) whose letters (symbols) are taken from an alphabet and are well-formed according to a specific set of rules, grammar. Let $\lang= <\Sigma, \Phi>$ be a formal language where: $$\begin{aligned}
    \Sigma &= \{S_1, S_2, \cdots, S_n\} \text{ is an alphabet,}\\
    \Phi &= {\Phi_1 \cup \Phi_2 \cup \cdots \cup \Phi_k} \text{ is a set of operations, the grammar,}
\end{aligned}$$ and: $$\begin{aligned}
    \Phi_1 &\text{ is the set of unary operations}, \nonumber\\
    \Phi_2 &\text{ is the set of binary operations}, \nonumber\\
    \cdots &\nonumber \\
    \Phi_k &\text{ is the set of k-ary operations.}\nonumber
\end{aligned}$$ A formal language allows a quantitative description of a state of knowledge and defines how this state can be updated on new evidence.[^32]

With this definition, we can also think that a formal language is what @sowinski2016 calls a *realm of discourse*, all the valid formed *strings*[^33] that one can derive; everything one can *say* about Nature.

Interestingly, formal languages allow us to manipulate representations of the environment without dealing with their semantics. They are the basis of *"Turing's strange inversion"*, (see [\[turing_strange_inversion\]][2]) by doing allowed operations on strings, computers can compute at a superhuman speed and accuracy without ever comprehending what they are doing.

### From Rationalism to Propositional Calculus {#sec:from_rationalism}

##### Rational Agents

can form representations of a complex world, use deduction as the inference process to derive updated representations, and use these new representations to decide what to do. In other words, rational agents are the consequence of the epistemological view of *rationalism*.

When a rational agent establishes a particular statement's truth value, all statements formed in her knowledge base from that statement instantly feel that update. Therefore, a rational agent cannot hold contradictions.

##### Desiderata for a rational language {#sec:desiderata_language}

We want to build a language for rational agents with the following desired characteristics:

I.  **knowledge is absolute**[]{#absolute_truth label="absolute_truth"}; a sentence[^34] can be either true or false;

II. **unambiguous**[]{#unambiguous label="unambiguous"}, a constructed sentence can only have one meaning;

III. **consistent**; a language without paradoxes, whatever path chosen to derive a sentence truth value will lead to the same assignment;[]{#rational_consistency label="rational_consistency"}

IV. **minimal**; uses the most reduced set of symbols possible.[]{#rational_minimality label="rational_minimality"}

Let $\lang_R= <\Sigma_R, \Phi_R>$ be the formal language built from these constraints, where sentences are either axiom symbols or compounded sentences formed using special symbols called operators, each operator denoting one operation, $\phi \in \Phi_R$.

It is possible to prove[]{#future:prove_minimal_language_logic label="future:prove_minimal_language_logic"} that $\lang_R$ only needs one operator [@sowinski2016; @jaynes2003]: [NAND]{.sans-serif} (or [XOR]{.sans-serif}), and it is also equivalent to Propositional Calculus.[^35] In other words, Logic is the language that emerges from our desiderata, from rationalism. **Logic is the language of mathematics**.

A point worth mentioning is that using Logic as an agent formal language means the **implicit acceptance** of the constraints above.

### From Empiricism to Probability Theory {#sec:from_empiricism}

The constraints that lead to Logic are very restrictive to use in the real-world; rational language has a comparatively small *realm of discourse*. Hume would say that it is only helpful for *relations of ideas*, talking in the abstract, and not for *matters of facts*, talking about reality.

A realm of discourse to talk about reality needs at least the empiricist perspective where knowledge is justified belief, and that one should *weigh her beliefs to the evidence.* The quantity that specifies to what degree we believe a proposition is true is constrained by other beliefs, i.e., previous experience and evidence gathered.

##### Sceptical Agents {#sec:sceptical_agents}

In the sceptical agent, the one derived from the empiricist epistemology (authors have called these agents epistemic agents [@caticha2008], idealised epistemic agents [@sowinski2016] or robots [@jaynes2003]), beliefs are not independent of each other [@caticha2008], they form an interconnected web that is the agent's knowledge base. The update mechanism, its inference method, follows the principle of minimality, i.e. it tries to minimise the change in the knowledge base.

##### Desiderata for a sceptical language {#sec:desiderata_language_sceptical}

As we did for rational agents, let us state a set of desired characteristics for the language of science, $\lang_S= <\Sigma_S, \Phi_S>$ [^36]:

I.  **Knowledge is a set of beliefs, quantifiable by real numbers and dependent on prior evidence [@sowinski2016; @caticha2008; @jaynes2003]:**[]{#beliefs label="beliefs"} Let $S_i \in \Sigma_S$ be sentences about the world. Given any two statements $S_1$, $S_2$, the agent must be able to say that $S_1$ is more plausible than $S_2$, or that $S_2$ is more plausible than $S_1$ or that $S_1$ and $S_2$ are equally plausible. Thus we can list statements in an increasing plausibility order. Real numbers can represent this transitive ordering.[^37]

    Let $b$ be a measure of degrees of belief in $S$ given some previous knowledge $K$: [^38]
\
    \begin{aligned}
            &b: \Sigma_S \to \Real\\
            &b: S \mapsto b(S|K)
    \end{aligned}
\
     Here we capture that plausibility (degrees of belief) is not a function of a sentence, but a relation between a sentence and a given assumed prior knowledge $K$.


II. **"Common sense:"**[]{#common_sense label="common_sense"}

    The plausibility of compound sentences should be related by some logical function to the plausibility of the sentences that form them. We already showed that a minimal rational language has only one operator. Here, instead of using the [NAND]{.sans-serif} operator, for a matter of familiarity, let us use the almost minimal language with the operators [NOT]{.sans-serif} ($\neg$) and [AND]{.sans-serif} ($\land$). In this setting, we are saying there are such functions $f$ and $g$ that [@sowinski2016]: 
\
    \begin{aligned}
            &b(\neg S|K) = f[b(S|K)] \tag{NOT}\\
            &b(S-1 \land S_2 | K) = g[b(S_1|K), b(S_1|S_2), b(S_2|K), b(S_2|S_1)]
    \end{aligned}
\

III. **Consistency:** The functions $f$ and $g$ must be consistent with the grammar $\Phi$ (production rules). Consistency guarantees that whatever path used to compute the plausibility of a statement in the context of the same knowledge web (the same set of constraints) must lead to the same degree of belief.[]{#consistency label="consistency"}

     (a) Beliefs that depend on multiple propositions cannot depend on the order in which they are presented.[]{#axiom:order label="axiom:order"}

     (b) No proposition can be arbitrarily ignored.

     (c) Propositions that are identical must be assigned the same degree of belief.

Such desiderata have a name; it is known as Cox's axioms[]{#cox label="cox"}, and one can derive the Sum Rule and the Product Rule (see [1.4]) from them, therefore, also the Bayes' Theorem ([1.9]), and reverse-engineer Kolmogorov's Axioms of Probability Theory (that will be seen in [\[sec:kolmogorov_axioms\]][3], [\[fig:kolmogorov\]][4])[]{#future:cox_to_kolmogorov label="future:cox_to_kolmogorov"} [@sowinski2016; @jaynes2003; @caticha2008; @terenin2015].

In other words, Probability Theory is the language that emerges from our desiderata, from empiricism. "**Probability theory is the Logic of Science**" [@jaynes2003], and our measure $b$ is usually called probability $P$.

Again, here we explicit that by using Bayesian inference to build and communicate concepts of the world (models), we are assuming Cox's axioms above.

### Assumptions and their consequences

Let us take this opportunity to explore what some assumptions mean to human intelligence in particular. It is indisputable[^39] that humans are not rational, neither sceptical agents. The whole idea of imagining an epistemic agent is a consequence of addressing intelligence without human complexities.

However, are humans irrational because of biology or psychology? Are we irrational for lack of will, or could it be that Nature wires the human brain in a way that pr*events* us from following these axioms? Here we argue that biology has an important role. Researchers have found, for instance, that visual acuity can be permanently impaired if there is a sensory deficit during early post-natal development [@wiesel:1982]. Futhermore, if the human brain is not exposed to some samples in its infancy, it will never achieve the accuracy level if it had experienced them, regardless of experiencing those examples later. In other words, *human beliefs depend on the order in which pieces of evidence are presented*, contradicting Cox's axiom [\[axiom:order\]][5].

## Formalizing Probability Theory

We derived Cox's axioms from a list of desired properties of the language for sceptical agents. We also know that it is possible to derive Kolmogorov's Axioms (which will be defined soon in [\[sec:kolmogorov_axioms\]][3]) from those axioms. In the next sections, we will use the Kolmogorov Axioms to formalise Probability theory.

Several concepts in the following sections are *relations of ideas*, not *matters of fact*. For example, the probability of an *event* E, P(E), can be computed by marginalisation (as we will show in [1.8]), but as discussed before, there are no beliefs in a vacuum. In reality, there is only the probability of an *event* E given some background knowledge $K$. This change of epistemological perspective is essential to be remembered now that we will expose the idealised development of Probability Theory.

## Experiments, Sample Spaces and Events

The set of possible outcomes of an ***experiment*** is the **sample space** $\Omega$. Let us use the canonical *experiment* of rolling a dice. In this experiment, the sample space is: $$\begin{aligned}
    \Omega = \left\{\epsdice{1},\epsdice{2},\epsdice{3},\epsdice{4},\epsdice{5},\epsdice{6} \right\}
\end{aligned}$$ An **outcome** or **realisation** is a point $\omega \in \Omega$: $$\begin{aligned}
    \omega_3&=\epsdice{3}\\
    \Omega &= \left\{\omega_1=\epsdice{1},\cdots,\omega_6=\epsdice{6} \right\}.
\end{aligned}$$ An **Event** is something that can be said about the *experiment*, "The dice rolled to an odd number". It is a true proposition. Nevertheless, easier than writing so much, we denote *events* with letters. **Events are subsets of $\Omega$** (see [\[fig:event_A\]][6]). $$\begin{aligned}
    A &= \left\{\va_1=\epsdice{1}, \va_2=\epsdice{3}, \va_3=\epsdice{5} \right\}\\
    A &\subset \Omega
\end{aligned}$$ We say that $A_1, A_2, \cdots$ are **mutually exclusive** or **disjoint** *events* if $A_i \cap A_j=\emptyset, \forall i\neq j$. For example, $A$ is the *event* "the dice rolled to the value 5" and $B$ is the *event* "the dice rolled to an even number". In this case, $A$ and $B$ are disjoint (see [\[fig:disjoint_events\]][7]).

::: sidecaption
Events, disjoint events and partitions.
:::

A **partition** of $\Omega$ is a sequence of disjoint events (sets) $A_i$ (see [\[fig:partition\]][8]), where: $$\begin{aligned}
    A_1, A_2, \cdots A_i \text{ s.t. } (A_1 \cup A_2 \cup A_3 \cdots = \bigcup\limits_{i=1}^{\infty} A_i) = \Omega
\end{aligned}$$

## Kolmogorov's definition of Probability {#sec:probability}

[]{#sec:kolmogorov_axioms label="sec:kolmogorov_axioms"}

::: definition
A function $P: \powerset(\Omega) \to \sR$ that maps any *event* $A$ to a real number $P(A)$ is called the **probability measure** or a **probability distribution** if it satisfies Kolmogorov's axioms [@wasserman2013]:

1.  $P(A)\geq 0, \forall A$

2.  $P(\Omega)=1$

3.  If $A$ and $B$ are disjoint, i.e. $A \ind B$,[]{#axiom:disjoint label="axiom:disjoint"} $$\begin{aligned}
                P(A \lor B)= P(A)+P(B)\label{eq:sum_rule}\tag{Sum Rule}
            
    \end{aligned}$$
:::

Visually, we can represent the probability of an *event* $A$, $P(A)$, as the proportion of the sample space the *event* occupies. To differentiate *events* from their probabilities, we will shade the area of the *event*.

::: sidecaption
Kolmogorov's Axioms and their direct consequences.[]{#fig:kolmogorov_axioms label="fig:kolmogorov_axioms"}
:::

Directly from the Kolmogorov Axioms, one can derive [@jaynes2003] other properties (see [\[fig:axiom1, fig:axiom2, fig:axiom3\]][9]): $$\begin{aligned}
P(\emptyset)&=0\\
B \subset A &\implies P(B) \leq P(A)\\
0 &\leq P(A) \leq 1\\
P(\bar{A})&=1-P(A).
\end{aligned}$$

## Joint event

::: definition
A joint *event* (A, B) is the set of outcomes where: $$(A, B) = {\omega \in \Omega: (\omega \in A \cap B) }$$ Therefore, $$P(A, B) =P({\omega \in \Omega: (\omega \in A \cap B) })$$
:::

When talking about *events* as propositions, it is straightforward to use logic notation $P(A \land B)$, but when we start to use *random variables* ([1.10]), we will adopt the shorthand notation $P(\rvA, \rvB)$.

## Independent events {#sec:independent_events}

::: definition
[]{#def:independence label="def:independence"} Events $A$ and $B$ are **independent** ($A \ind B$) if: $$\begin{aligned}
A\neq \emptyset, B\neq \emptyset \implies P(A)>0, P(B)>0\label{eq:P(A, B)>0}\\
P(A, B) = P(A \land B) = P(A) \cdot P(B)\label{eq:Product_Rule}\\
\nonumber \tag{Product Rule}
\end{aligned}$$
:::

**Disjoint *events* cannot be independent**, since (from [\[eq:P(A, B)\>0\]][10]) $P(A) \cdot P(B)> 0$, but as disjoint *events* ([\[fig:disjoint_events\]][7]) $P(A \land B)=P(\emptyset)=0$, leading to contradiction.

Independence can be assumed or derived by verifying: $$\begin{aligned}
P(A \land B)= P(A) \cdot P(B).\\
\nonumber \tag{Independent variables}
\end{aligned}$$

## Conditional probability

As we have explained before ([1.1.3.0.1]), the plausibility of an outcome or a set of outcomes depends on a web of interconnected prior beliefs. So, what exists are probabilities *conditional* to a given prior assumption.

::: definition
If $P(B)>0$ then the **conditional probability** of A given B is: $$\begin{aligned}
\label{eq:conditional_probability}
P(A|B) \eqdef \frac{P(A,B)}{P(B)}
\end{aligned}$$ $$\begin{aligned}
\label{eq:joint_probability}
P(A, B) \eqdef P(A|B)\cdot P(B)
\end{aligned}$$
:::

Except if $P(A) \equiv P(B)$, $P(A|B) \neq P(B|A)$. Also, $P(A|B)=P(A) \iff A \ind B$.[^310]

## Marginal probability {#marginalisation}

::: theorem
Let $A_1, \cdots, A_k$ be a partition of $\Omega$. Then, for any *event* B, $$\begin{aligned}
P(B)=\sum_{i=1}^k P(B|A_i)\cdot P(A_i)\label{eq:law_of_total_probabilities} 
\end{aligned}$$
:::

::: proof
*Proof.* [^311] Define $C_i = (B,A_i)$. Let $C_1, \cdots C_k$ be disjoint and $B = \bigcup\limits_{i=1}^k C_i$.\
Therefore:

$$\begin{aligned}
        P(B) &\triangleq P(\bigcup\limits_{i=1}^k C_i)
        \overset{\text{\ref{eq:sum_rule}}}{=} \sum_i P(C_i)\\
        &\triangleq \sum_i P(B,A_i)
        \overset{\text{\ref{eq:conditional_probability}}}{=} \sum_{i=1}^k P(B|A_i)\cdot P(A_i) \tag{Law of Total Probability}
    
\end{aligned}$$ ◻
:::

## Bayes' theorem {#sec:bayes_theorem}

::: theorem
Let $A_1, \cdots, A_k$ be a partition of $\Omega$ s.t. $P(A_i)>0, \forall i$ then, $\forall i=1, \cdots, k$: $$\begin{aligned}
        P(A_i|B)= \frac{P(B|A_i)\cdot P(A_i)}{\sum_i P(B|A_i)\cdot P(A_i)}
    
\end{aligned}$$
:::

::: proof
*Proof.* From equations [\[eq:conditional_probability\]][11], [\[eq:joint_probability\]][12] and [\[eq:law_of_total_probabilities\]][13]: $$\begin{aligned}
        P(A_i|B)&\overset{\text{\ref{eq:conditional_probability}}}{=}\frac{P(A_i,B)}{P(B)} \overset{\text{\ref{eq:joint_probability}}}{=} \frac{P(B|A_i) \cdot P(A_i)}{P(B)}  \\
        &\overset{\text{\ref{eq:law_of_total_probabilities}}}{=}\frac{P(B|A_i)\cdot P(A_i)}{\sum_{i=1}^k P(B|A_i)\cdot P(A_i)}
    
\end{aligned}$$ ◻
:::

We call $P(A_i)$ the **prior** of A, and $P(A_i|B)$ the **posterior** probability of A.

## Random variables {#sec:random_variables}

::: definition
A **random variable** is a mapping $\rvX:\Omega \to \Real$ that assigns a real number $\rvX(\omega)$ to each outcome $\omega$, $\omega \mapsto \rvX(\omega)$.
:::

Given a random variable $\rvX$, the probability of an outcome $\rx$ can be expressed as: $$\begin{aligned}
    P(\rvX=\rx) = P(\rvX^{-1}(\rx)) = P(\{\omega \in \Omega: \rvX(\omega)=\rx\})\label{eq:P(X=x)} 
\end{aligned}$$

Several works on Probability Theory choose to start by defining random variables, rarely mentioning sample spaces, *events* or the connection with logical propositions.

This usual approach is, nevertheless, confusing. Beyond the fact that random variables are not variables, but functions, nor random, they model uncertain *events*; it is hard to grasp what random variables are without understanding their reasons for being.

The difference between a random variable $\rvX$ and its "realisation" is the difference between a distribution and a sample from that distribution. In particular, a random variable $\rvX$ is "formalised" in terms of a function from the sample space to some result space, typically $\Real$. The realisation of a random variable is "what you get" when an *experiment* is run, and you apply $\rvX$ to *events* that happened.

### Notation abuse

If a *random variable* is a function, how can we write $P(\rvX=4)$ or $P(\rvX > 7)$? Such confusion is due to some notation abuse that became standard in works on probability theory. It is not easy to grasp it initially, but the explanation was already stated at [\[eq:P(X=x)\]][14]. $P(\rvX=\rx)$ is a shorthand for $P(\rvX^{-1}(\rx))$.

Technically, a *random variable* is a function. In practice, it is just a mathematical tool to help us associate propositions with numbers. It is called a *random variable* because the notation abuse treats the function as a variable.

To help clear up such confusion, let us recap a little the notation we have established before:

In the canonical *experiment* of rolling a dice, instead of writing the proposition *"The dice will roll to number 4."* plausibility is $\frac{1}{6}$, it is easier to assign a letter to the proposition, or as we called the event. Let us use *event* $D$ to represent the proposition. Then, we can use $P(D)=\frac{1}{6}$. Now, we are going one step further; instead of using the *event* $D$ we use the *random variable* $\rvD$, in italic, and say $P(\rvD=4)=\frac{1}{6}$.

Notice the difference between a *random variable* and an *event*:[^312] $\rvD$ could assume any value (even $\rvD=7$, which is outside of our *sample space*). Would it not be easier then to use an index to the *event* letters, $D_4$ to value 4, and $D_1$ to value 1, etc.? Not really.

Besides providing this shorter notation, the mapping of the random variable allows us to manipulate *events* as numbers: for example, we can chart probability distributions using random variables, which we cannot cope with *events*.

## Probability Distributions

::: definition
A probability distribution of a discrete random variable $\rvX$ or **probability mass function (pmf)** is a function $p: \Omega \to [0,1]$ that provides the probabilities of occurrence of different possible outcomes in an *experiment* (sample space):

$$\begin{aligned}
        p(\rx) = P(\rvX = \rx), \tag{pmf}
    
\end{aligned}$$
:::

If $\rvX$ is continuous, $P(\rvX=\rx)\to 0$, therefore we need to use intervals in this case.

::: definition
A probability distribution of a countinous random variable $\rvX$ in an interval $A$, or **probability density function (pdf)** is a function $p(\rx)$ that measures the probability of randomly selecting a value within the interval $A=[a, b]$, as the area under its curve for the interval A:

::: flalign
P(A) &= P\[a b\] = \_a\^b p()   d,\
&

::: cases
p() , x\
\_\^ p()   d= 1
:::
:::
:::

Now that we explained what distributions are,[^313] here we highlight some useful distributions:

### Statistical model {#sec:statistical_model}

A statistical model is a function $p_{\theta}(\rx) \equiv p(\rx | \theta)$ representing the relationship between a parameter[^314] $\theta$ and potential outcomes $\rx$ of a random variable $\rvX$. In practice, we usually define a statistical model of a stochastic process for which we do not know the real distribution. Therefore, the parameter $\theta$ has to be inferred from the observed data.

### Uniform distribution {#sec:uniform_distribution}

$\nonumber \\\rvX \sim \text{Uniform}(a,b)$, if:\
$$\begin{aligned}
    p(\rx)=
    \begin{cases}
        \frac{1}{b-a} & x \in [a,b]\\
        0 & \rx \notin [a,b]
    \end{cases}
\end{aligned}$$

### Normal distribution

$\nonumber \\\rvX \sim \mathcal{N}(\mu, \sigma^2)$, if: $$\begin{aligned}
    p(\rx)=\frac{1}{\sigma \sqrt{2\pi}}\exp{\Biggl{\{}{-\frac{1}{2\sigma^2}{(x-\mu)}^2}\Biggr{\}}}, \\~x \in \Real \\
\end{aligned}$$ where $\mu \in \Real$ (mean) and $\sigma > 0$ (standard deviation). We say that $\rvX$ has a **standard Normal distribution** if $\mu = 0$, $\sigma =1$.

### Exponential distribution

$\rvX \sim \text{Exp}(\lambda)$, if: $$\begin{aligned}
    p(\rx;\lambda) =
    \begin{cases}
        \lambda e^{-\lambda \rx} & \rx \ge 0, \\
        0 & \rx < 0.
    \end{cases}
\end{aligned}$$ where $\lambda > 0$ is the *rate parameter* of the distribution.

## Joint Distributions

::: definition
Given a pair of discrete random variables $\rvX$ and $\rvY$, we define the **joint mass function** by $p(\rx, \ry)=P(\rvX=\rx,\rvY=\ry)$.
:::

::: definition
Given a pair of continuous random variables $\rvX$ and $\rvY$, we define the **joint density function** by $p(\rx, \ry)$, where:

i.  $p(\rx, \ry) \geq 0$

ii. $\iint_{-\infty}^{\infty} p(\rx,\ry) \, d\rx d\ry =1$

iii. $\forall A \subset \Real \times \Real, P((\rvX,\rvY)\in A)=\iint_{A}p(\rx,\ry)\, d\rx d\ry$.
:::

## Expectancy, Variance and Covariance

::: definition
The **expected value** or **mean** of $\rvX$ is: $$\begin{aligned}
        \E (\rvX)=\langle \rvX \rangle = \SumInt_x \rx~p(\rx)~dx = \mu = \mu_X
    
\end{aligned}$$
:::

::: theorem
Let $\rvX_1, \cdots, \rvX_n$ be random variables and $a_1, \cdots, a_n$ be constants, then from the *Sum Rule*: $$\begin{aligned}
        \E \biggl(\sum_i a_i\rvX_i\biggr)=\sum_i a_i(\E (\rvX_i))
    
\end{aligned}$$
:::

::: theorem
Let $\rvX_1, \cdots, \rvX_n$ be independent random variables, then from the *Product Rule*: $$\begin{aligned}
        \E (\prod_i \rvX_i)=\prod_i \E (\rvX_i)
    
\end{aligned}$$
:::

::: definition
Let $\rvX$ be a random variable with mean $\mu$. The **variance** of $\rvX$ is defined by: $$\begin{aligned}
        \sigma^2 = \sigma_{\rvX}^2 =\E {(\rvX - \mu)}^2
    
\end{aligned}$$ assumming this expectation exists. The standard deviation is $\sigma$.
:::

::: definition
Let ${\rvX}$ and ${\rvY}$ be random variables with means $\mu_{\rvX}$ and $\mu_{\rvY}$, and with standard deviations $\sigma_{\rvX}$ and $\sigma_{\rvY}$. The **covariance** between ${\rvX}$ and ${\rvY}$ is defined as [@wasserman2013 p.74]: $$\begin{aligned}
        \operatorname{Cov}({\rvX},{\rvY}) = \E (({\rvX} - \mu_{\rvX})({\rvY} - \mu_{\rvY}))
    
\end{aligned}$$ and the correlation as: $$\begin{aligned}
        \rho = \rho_{{\rvX},{\rvY}} = \rho({\rvX},{\rvY}) = \frac{\operatorname{Cov}({\rvX},{\rvY})}{\sigma_{\rvX} \sigma_{\rvY}}
    
\end{aligned}$$
:::

::: theorem
The covariance satisfies: $$\begin{aligned}
        \operatorname{Cov}({\rvX},{\rvY})=\E ({\rvX}{\rvY})- \E({\rvX}) \E({\rvY}).
    
\end{aligned}$$
:::

## Independent Sampling

A *sample* is a set of examples[^315] drawn from a distribution. One common assumption in Machine Learning Theory is that examples are *identically and independently distributed --- i.i.d.* This means that the probability of obtaining a first training example. $(\rx_1, \ry_1)$ does not affect which $(\rx_2, \ry_2)$ will be drawn in the following observation.

The i.i.d. assumption is useful wherever a census of the population of interest, knowing all possible values, is unfeasible. In this usual case, data analysis is carried out using a sample to represent the population. When the sample is i.i.d., each example in the population has the same chance of being observed ([\[fig:sampling\]][15] --- left).

If there is a constraint on which examples of the population are sampled, we say that the sample is *biased* ([\[fig:sampling\]][15] --- right).

## Concluding Remarks

This chapter derived *Logic* from the definition of knowledge as absolute truth and *Probability Theory* from knowledge as justified beliefs ([\[sec:from_rationalism, sec:from_empiricism\]][16]). To remind that our definition of knowledge is the basis for the Bayesian perspective of probability and that inference methods are languages, we can say (and prefer) that we derived *Bayesian inference* as the language of science. We proved what we claimed in the previous chapter ([\[ch:artificial_intelligence\]][17]).

We needed to define *formal languages* ([1.1.1]) and assume desiderata for the languages we wanted to build formally ([\[sec:desiderata_language,sec:desiderata_language_sceptical\]][18]). We called *rational agents* the epistemic agents that use Logic as its inference method, and *sceptical agents* use Bayesian inference.

We found out that the desiderata for the sceptical language are equivalent to Cox's axioms ([\[cox\]][19]). From Cox's axioms, it is possible to derive Kolmogorov's axioms of Probability Theory. Which made us conclude that Bayesian inference is the language of science.[^316]

From the derivation, we did a basic Statistics review (influenced by [@wasserman2013]). Many essential topics were left out from this short review chapter, where the focus was to present the concepts that we will use later on in this dissertation.

### Assumptions

1.  A definition of intelligence ([\[def:intelligence\]][20]);

2.  A epistemic choice on the definition of Knowledge ([\[sec:rationalism, sec:empiricism\]][21]);

3.  A definition of formal language;

4.  Common assumptions of the epistemic agent language:

    1.  consistency ([1.1.3.0.2], [\[consistency\]][22] and [1.1.2.0.2], [\[rational_consistency\]][23]);

    2.  minimality ([1.1.2.0.2], [\[rational_minimality\]][24]).

5.  Assumption of the rational agent language:

    1.  knowledge is absolute, a set of true or false sentences ([1.1.2.0.2], [\[absolute_truth\]][25]);

    2.  the language must be unambiguous ([1.1.2.0.2], [\[unambiguous\]][26]).

6.  Assumption of the sceptical agent language:

    1.  Knowledge is a set of beliefs, quantifiable by real numbers and dependent on prior evidence ([1.1.3.0.2], [\[beliefs\]][27]);

    2.  Common sense: The plausibility of compound sentences should be related by some logical function to the plausibility of the sentences that form them ([1.1.3.0.2], [\[common_sense\]][28]).

As we have settled that our focus is Deep Learning, which relates to the sceptical agent, we will abstain from keeping the rational language assumptions in our analysis and assume an epistemic agent is sceptical.

[^31]: We can take this idea further and think that at any moment, we need to communicate with our past selves to check if new evidence is consistent with our prior model.

[^32]: An inference method defines the rules for updating knowledge.

[^33]: Strings, words, sentences, propositions, formulae are names used interchangeably through the literature.

[^34]: A sentence can be either a single symbol or a string formed with several symbols according to the grammar.

[^35]: Proposition is synonym to sentence and Propositional Calculus is also known as Sentential Calculus.

[^36]:   also present this same idea of deriving probability theory from desiderata.

[^37]: We are implicitly assuming that the language we are building has infinite statements. A further discussion on this continuity assumption can be found in .

[^38]: Using $(S|K)$ in a function is a notation abuse that we accept to explain the idea better.

[^39]: Unless you are an economist.

[^310]: Venn diagrams are not helpful to see that the *events* are independent, as it all depends on the areas of intersection and the sizes of A and B, which are tricky to estimate without computational help.

[^311]: Remember: $(B, A) \equiv (B \cap A)$.

[^312]: An *event* can be seen as a special kind of *random variable*. , a random variable $\rvD$ is the truth function (also known as the indicator function) over an event $D$: $$\begin{aligned}
        \rvD=\truth_D
    \end{aligned}$$ That is the reason one can say that "*random variables* define *events*."

[^313]: In this dissertation, we will use $P(\rvX)$ to express the probability of a random variable, and $p(\rx)$ to represent a *pmf* or *pdf* of the random variable outcomes.

[^314]: In this dissertation we are interested in vector-valued $\theta$.

[^315]: In this dissertation, an element of a sampling is called an *example*.

[^316]: Our definition of knowledge hinted at a Bayesian perspective of knowledge.

  [1]: #blind_men {reference-type="ref" reference="blind_men"}
  [2]: #turing_strange_inversion {reference-type="ref" reference="turing_strange_inversion"}
  [1.4]: #sec:probability {reference-type="ref" reference="sec:probability"}
  [1.9]: #sec:bayes_theorem {reference-type="ref" reference="sec:bayes_theorem"}
  [3]: #sec:kolmogorov_axioms {reference-type="ref" reference="sec:kolmogorov_axioms"}
  [4]: #fig:kolmogorov {reference-type="ref" reference="fig:kolmogorov"}
  [5]: #axiom:order {reference-type="ref" reference="axiom:order"}
  [1.8]: #marginalisation {reference-type="ref" reference="marginalisation"}
  [6]: #fig:event_A {reference-type="ref" reference="fig:event_A"}
  [7]: #fig:disjoint_events {reference-type="ref" reference="fig:disjoint_events"}
  [8]: #fig:partition {reference-type="ref" reference="fig:partition"}
  [9]: #fig:axiom1, fig:axiom2, fig:axiom3 {reference-type="ref" reference="fig:axiom1, fig:axiom2, fig:axiom3"}
  [1.10]: #sec:random_variables {reference-type="ref" reference="sec:random_variables"}
  [10]: #eq:P(A, B)>0 {reference-type="eqref" reference="eq:P(A, B)>0"}
  [1.1.3.0.1]: #sec:sceptical_agents {reference-type="ref" reference="sec:sceptical_agents"}
  [11]: #eq:conditional_probability {reference-type="ref" reference="eq:conditional_probability"}
  [12]: #eq:joint_probability {reference-type="ref" reference="eq:joint_probability"}
  [13]: #eq:law_of_total_probabilities {reference-type="ref" reference="eq:law_of_total_probabilities"}
  [14]: #eq:P(X=x) {reference-type="eqref" reference="eq:P(X=x)"}
  [15]: #fig:sampling {reference-type="ref" reference="fig:sampling"}
  [16]: #sec:from_rationalism, sec:from_empiricism {reference-type="ref" reference="sec:from_rationalism, sec:from_empiricism"}
  [17]: #ch:artificial_intelligence {reference-type="ref" reference="ch:artificial_intelligence"}
  [1.1.1]: #sec:formal_language {reference-type="ref" reference="sec:formal_language"}
  [18]: #sec:desiderata_language,sec:desiderata_language_sceptical {reference-type="ref" reference="sec:desiderata_language,sec:desiderata_language_sceptical"}
  [19]: #cox {reference-type="ref" reference="cox"}
  [20]: #def:intelligence {reference-type="ref" reference="def:intelligence"}
  [21]: #sec:rationalism, sec:empiricism {reference-type="ref" reference="sec:rationalism, sec:empiricism"}
  [1.1.3.0.2]: #sec:desiderata_language_sceptical {reference-type="ref" reference="sec:desiderata_language_sceptical"}
  [22]: #consistency {reference-type="ref" reference="consistency"}
  [1.1.2.0.2]: #sec:desiderata_language {reference-type="ref" reference="sec:desiderata_language"}
  [23]: #rational_consistency {reference-type="ref" reference="rational_consistency"}
  [24]: #rational_minimality {reference-type="ref" reference="rational_minimality"}
  [25]: #absolute_truth {reference-type="ref" reference="absolute_truth"}
  [26]: #unambiguous {reference-type="ref" reference="unambiguous"}
  [27]: #beliefs {reference-type="ref" reference="beliefs"}
  [28]: #common_sense {reference-type="ref" reference="common_sense"}
