# Acknowledgements

This dissertation would not have been possible without the help of many people. I am very thankful to Teo de Campos, my supervisor, for the support and encouragement even when my interests led the work far from his comfort zone. I also thank my committee members, John Shawe-Taylor and Moacir Ponti, for investing the time to read and evaluate a dissertation that was way longer than expected.

Many thanks to my colleagues, especially Pedro Luz and Aloísio Dourado, for the collaboration and stimulating discussions. I am in- debted also to several UnB teachers: Daniel Guerreiro, Thiago Faleiros, Fabrício Braz, Li Weigang, Bruno Espinoza, Anderson Nascimento and many others. In particular, I want to thank Célia Ralha for all the kindness and guidance.

I thank everybody from the Knedle project and the LISA lab. I am also grateful for the support from Fundação de Apoio à Pesquisa do Distrito Federal(FAPDF[^1]) and Fundação de Empreendimentos Científicos e Tecnológicos (FINATEC).

I also acknowledge that without the bravery of Alexandra Elbakyan of Sci-hub, this would be a much poorer dissertation. I also would like to thank Friedrich Wiemer, Cassiano Rabelo and Aaron Turon. Without relying on their work2, I would never be able to de- velop the complex aesthetic of this document.

I need to thank my loved ones. My friends Gabriel Squeff, Eduardo Dimitrov and Erick Muzart read this dissertation’s early drafts even though it is not in their areas of interest. My brother Felipe, whose patience and support are crucial in all my endeavours. My parents, Leila and Klaus, and in-laws, Anna, Romero and Alessandro, for mak- ing the day-to-day life endurable. Lastly, my wife Júlia and daughter Luísa, for keeping me sane and happy.

[^1]: FAPDF/Projeto KnEDLe, convênio 07/2019